
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;


public class TenantsCheckIn extends javax.swing.JFrame {

    myConnection con= new myConnection();
    tCheckIn tc=new tCheckIn();
    SimpleDateFormat k = new SimpleDateFormat("yyyy-MM-dd");
    static String status ;
    static String statuss;
    
    public TenantsCheckIn() {
        initComponents();
        tableFill();
        this.setLocationRelativeTo(null);
        jDateChooser1.setMaxSelectableDate(new Date());
        jDateChooser1.setMinSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldphone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldhouseno = new javax.swing.JTextField();
        estName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        agName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        landName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldrent = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldsize = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        agPhone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        landPhone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setText("TENANTS CHECKIN");

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setText("Tenant ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 11, -1, 25));
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 11, 187, 25));
        jPanel1.add(jTextFieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 54, 187, 25));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("Tenant Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 54, -1, 25));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Phone");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 97, -1, 25));
        jPanel1.add(jTextFieldphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 97, 187, 25));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("House Number");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 11, -1, 25));

        jTextFieldhouseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldhousenoActionPerformed(evt);
            }
        });
        jTextFieldhouseno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldhousenoKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldhouseno, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 11, 187, 25));

        estName.setEditable(false);
        estName.setEnabled(false);
        estName.setFocusable(false);
        jPanel1.add(estName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 54, 187, 25));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("Estate Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 54, -1, 25));

        agName.setEditable(false);
        agName.setEnabled(false);
        agName.setFocusable(false);
        jPanel1.add(agName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 97, 187, 25));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("Agent Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 97, -1, 25));

        landName.setEditable(false);
        landName.setEnabled(false);
        landName.setFocusable(false);
        jPanel1.add(landName, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 13, 187, 25));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("Landlord Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 11, -1, 29));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "House No", "Estate Name", "Estate Class", "Size", "Rent", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 317, 980, 236));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("Rent");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 81, -1, 29));

        jTextFieldrent.setEditable(false);
        jTextFieldrent.setEnabled(false);
        jTextFieldrent.setFocusable(false);
        jPanel1.add(jTextFieldrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 83, 187, 25));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 255));
        jLabel10.setText("Size");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 128, -1, 29));

        jTextFieldsize.setEditable(false);
        jTextFieldsize.setEnabled(false);
        jTextFieldsize.setFocusable(false);
        jPanel1.add(jTextFieldsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 130, 187, 25));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 255, 255));
        jLabel11.setText("AVAILABLE HOUSES");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 274, -1, -1));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 255, 255));
        jLabel12.setText("Agent Phone");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 140, -1, 25));

        agPhone.setEditable(false);
        agPhone.setEnabled(false);
        agPhone.setFocusable(false);
        jPanel1.add(agPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 187, 25));

        jLabel13.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 255));
        jLabel13.setText("Landlord Phone");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(773, 46, -1, 29));

        landPhone.setEditable(false);
        landPhone.setEnabled(false);
        landPhone.setFocusable(false);
        jPanel1.add(landPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 48, 187, 25));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\Check-icon.png")); // NOI18N
        jButton1.setText("Checkin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 200, 40));

        jLabel14.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 255, 255));
        jLabel14.setText("Date");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 133, -1, 25));

        jDateChooser1.setDateFormatString("yyyy-MM-dd  HH:mm:ss");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 133, 187, 32));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void tableFill(){
        PreparedStatement pst;
        ResultSet rst;
        
        try {
            
            
            String q="SELECT houses.Number AS House_Number,estates.Name AS Estate_Name,estates.Class AS Estate_Class,houses.size AS House_Size,houses.Rent,houses.Status FROM houses INNER JOIN estates ON houses.Estate_ID=estates.ID";
            pst=con.createConnection().prepareStatement(q);
            rst=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rst));
            
        } catch (SQLException ex) {
            Logger.getLogger(TenantsCheckIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextFieldhousenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldhousenoKeyReleased
        try {
            // TODO add your handling code here:
            PreparedStatement st;
            ResultSet rs;
            String query="SELECT estates.Name AS Estate_Name,agents.Name AS Agent_Name,agents.Phone AS Agent_Phone,landlords.Name AS Landlord_Name,landlords.Phone AS Landlord_Phone,houses.Rent,houses.status,houses.Size FROM houses INNER JOIN estates ON houses.Estate_ID=estates.ID INNER JOIN agents ON houses.Agent_ID=agents.ID INNER JOIN landlords ON houses.Landlord_ID=landlords.ID WHERE houses.Number='"+jTextFieldhouseno.getText()+"';";
            String estatename,agentname,AgentPhone,LandlordName,LandlordPhone,rent,size;
            st=con.createConnection().prepareStatement(query);
            
            rs=st.executeQuery(query);
            if(rs.next()){
                estatename=rs.getString("Estate_Name");
                agentname=rs.getString("Agent_Name");
                AgentPhone=rs.getString("Agent_Phone");
                LandlordName=rs.getString("Landlord_Name");
                LandlordPhone=rs.getString("Landlord_Phone");
                rent=rs.getString("rent");
                size=rs.getString("size");
                status=rs.getString("status");
                estName.setText(estatename);
                agName.setText(agentname); 
                agPhone.setText(AgentPhone);  
                landName.setText(LandlordName);
                landPhone.setText(LandlordPhone);
                jTextFieldrent.setText(rent); 
                jTextFieldsize.setText(size);


 
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(TenantsCheckIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldhousenoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            String ID=String.valueOf(jTextFieldID.getText());
            String name=jTextFieldname.getText();
            String phone=String.valueOf(jTextFieldphone.getText());
            String houseno=String.valueOf(jTextFieldhouseno.getText());
            Date date=jDateChooser1.getDate();
            String q = k.format(date);
            
            PreparedStatement st;
            ResultSet rs;
            String query ="SELECT `Status` FROM `houses` WHERE `Number`='"+jTextFieldhouseno.getText()+"';";
            
            st=con.createConnection().prepareStatement(query);
            
            rs=st.executeQuery(query);
             if(rs.next()){
                 statuss=rs.getString("status");
             }
            
            
            
            if(ID.trim().equals("") ||name.trim().equals("") || phone.trim().equals("") || houseno.trim().equals("")|| date.equals("") ){
                
                JOptionPane.showMessageDialog(rootPane, "Required Fields -> ID, Name, Phone ,House number and Date", "Empty fields", JOptionPane.WARNING_MESSAGE);
                
            }
            else{
                if(statuss=="Taken"){
                  JOptionPane.showMessageDialog(rootPane, "House_Taken", "House_Taken", JOptionPane.ERROR_MESSAGE);  
                    
                }
                else{
                
                
                if(tc.addTenant(ID, name, phone,houseno, q)){
                    JOptionPane.showMessageDialog(rootPane, "Successful", "Add_Tenant", JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Unsuccessful", "Add_Tenant Error", JOptionPane.ERROR_MESSAGE);
                    
                }
                String number=String.valueOf(jTextFieldhouseno.getText());
                tc.UpdateHouseStatus(number);
                
                
            }
            }
                       
            //}
            
            //  else{
            //JOptionPane.showMessageDialog(rootPane, "The Date entered must be today", "Check-In Date Error", JOptionPane.ERROR_MESSAGE);
            
            //}
            
            jTable2.setModel(new DefaultTableModel(null, new Object[]{""}));
            tableFill();
        } catch (SQLException ex) {
            Logger.getLogger(TenantsCheckIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldhousenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldhousenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldhousenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TenantsCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TenantsCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TenantsCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TenantsCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TenantsCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agName;
    private javax.swing.JTextField agPhone;
    private javax.swing.JTextField estName;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldhouseno;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldphone;
    private javax.swing.JTextField jTextFieldrent;
    private javax.swing.JTextField jTextFieldsize;
    private javax.swing.JTextField landName;
    private javax.swing.JTextField landPhone;
    // End of variables declaration//GEN-END:variables
}
