
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class House_info extends javax.swing.JFrame {

    myConnection cn= new myConnection();
    Houses hse=new Houses();
    public House_info() {
        initComponents();
        ComboLand(); 
        ComboEst(); 
        ComboAg();
        hse.filljTable(jTable2);
        this.setLocationRelativeTo(null);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldrent = new javax.swing.JTextField();
        jComboBoxLandID = new javax.swing.JComboBox();
        jComboBoxStat = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxEstID = new javax.swing.JComboBox();
        jComboBoxAgID1 = new javax.swing.JComboBox();
        jComboBoxSize = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(0, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("HOUSE INFO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(374, 374, 374))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("NUMBER");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 31));

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 192, 26));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("LANDLORD ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 100, 31));

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("AGENT'S ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 31));

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("RENT");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 90, 31));

        jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("SIZE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, 31));

        jLabel7.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("STATUS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, 31));

        jTextFieldrent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldrentActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 192, 31));

        jComboBoxLandID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- - Select- -" }));
        jPanel1.add(jComboBoxLandID, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 192, 31));

        jComboBoxStat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- -Select - -", "Taken", "Not Taken" }));
        jComboBoxStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxStat, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, 192, 31));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ESTATE ID", "LANDLORD ID", "AGENT ID", "RENT", "SIZE", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 940, 220));

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\remove item.png")); // NOI18N
        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 150, 41));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\edit1.png")); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 100, 41));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\addnew2.png")); // NOI18N
        jButton1.setText("Add new house");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 180, 41));

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\clear.png")); // NOI18N
        jButton4.setText("Clear All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 170, 41));

        jButton6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\refresh1.png")); // NOI18N
        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 298, 41));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("ESTATE ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, 31));

        jComboBoxEstID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "_ _Select_ _" }));
        jPanel1.add(jComboBoxEstID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 192, 31));

        jComboBoxAgID1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- -Select - -" }));
        jComboBoxAgID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAgID1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxAgID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 192, 31));

        jComboBoxSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- -Select- -", "Big", "Medium", "Small" }));
        jPanel1.add(jComboBoxSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldrentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldrentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldrentActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel mdl = (DefaultTableModel)jTable2.getModel();

        int rowIndex = jTable2.getSelectedRow();

        jTextFieldID.setText(mdl.getValueAt(rowIndex,0).toString());
        jComboBoxEstID.setSelectedItem(mdl.getValueAt(rowIndex,1)); 
        jComboBoxLandID.setSelectedItem(mdl.getValueAt(rowIndex,2));
        jComboBoxAgID1.setSelectedItem(mdl.getValueAt(rowIndex,3));
        jTextFieldrent.setText(mdl.getValueAt(rowIndex,4).toString()); 
        jComboBoxSize.setSelectedItem(mdl.getValueAt(rowIndex,5));
        jComboBoxStat.setSelectedItem(mdl.getValueAt(rowIndex,6));

        


    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ID= String.valueOf(jTextFieldID.getText());
         if(hse.removeHouse(ID)){
            JOptionPane.showMessageDialog(rootPane, "House Successfully Deleted", "Delete_Agent", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Unsuccessful deletion", "Delete_Agent Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Number=String.valueOf(jTextFieldID.getText()); 
        String EstateID=String.valueOf(jComboBoxEstID.getSelectedItem());
        String LandlordID=String.valueOf(jComboBoxLandID.getSelectedItem());
        String AgentID =String.valueOf(jComboBoxAgID1.getSelectedItem());  
        String rent=jTextFieldrent.getText(); 
        String size=String.valueOf(jComboBoxSize.getSelectedItem());
        String status=String.valueOf(jComboBoxStat.getSelectedItem());





        if(hse.editHouse(Number, EstateID, LandlordID,AgentID,rent,size,status)){
            JOptionPane.showMessageDialog(rootPane, "Agent Successfully Updated", "Edit_Agent", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Unsuccessful", "Edit_Agent Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String Number=String.valueOf(jTextFieldID.getText()); 
        String EstateID=String.valueOf(jComboBoxEstID.getSelectedItem());
        String LandlordID=String.valueOf(jComboBoxLandID.getSelectedItem());
        String AgentID =String.valueOf(jComboBoxAgID1.getSelectedItem());  
        String rent=jTextFieldrent.getText(); 
        String size=String.valueOf(jComboBoxSize.getSelectedItem());
        String status=String.valueOf(jComboBoxStat.getSelectedItem());

        if(hse.addHouse(Number, EstateID, LandlordID,AgentID,rent,size,status)){
            JOptionPane.showMessageDialog(rootPane, "Successful", "Add_House", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Unsuccessful", "Add_House_Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextFieldID.setText(null);
        jTextFieldrent.setText(null); 
        jComboBoxSize.setSelectedIndex(0);   
        jComboBoxStat.setSelectedIndex(0);   

        jComboBoxEstID.setSelectedIndex(0);   
        jComboBoxLandID.setSelectedIndex(0); 
        jComboBoxAgID1.setSelectedIndex(0);


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
          jTable2.setModel(new DefaultTableModel(null, new Object[]{"Number","EstateID","LandlordID","AgentID","Rent","size","status"}));
        hse.filljTable(jTable2);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBoxStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatActionPerformed

    private void jComboBoxAgID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAgID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAgID1ActionPerformed

   
    
    public void ComboLand(){
              PreparedStatement st;
        ResultSet  rs;
        String querySelection = "SELECT * FROM `landlords`";
        
         try {
             st=cn.createConnection().prepareStatement(querySelection);
              rs = st.executeQuery();
              
              while(rs.next()){
                  String LandlordID=rs.getString("ID");
                  jComboBoxLandID.addItem(LandlordID);
              }
             
         } catch (SQLException ex) {
             Logger.getLogger(Houses.class.getName()).log(Level.SEVERE, null, ex);
         }
            
           
            
        
        
    }
    
      public void ComboEst(){
              PreparedStatement st;
        ResultSet  rs;
        String querySelection = "SELECT * FROM `estates`";
        
         try {
             st=cn.createConnection().prepareStatement(querySelection);
              rs = st.executeQuery();
              
              while(rs.next()){
                  String EstateID=rs.getString("ID");
                  jComboBoxEstID.addItem(EstateID);
              }
             
         } catch (SQLException ex) {
             Logger.getLogger(Houses.class.getName()).log(Level.SEVERE, null, ex);
         }
            
           
            
        
        
    }
      
        public void ComboAg(){
              PreparedStatement st;
        ResultSet  rs;
        String querySelection = "SELECT * FROM `agents`";
        
         try {
             st=cn.createConnection().prepareStatement(querySelection);
              rs = st.executeQuery();
              
              while(rs.next()){
                  String AgentID=rs.getString("ID");
                  jComboBoxAgID1.addItem(AgentID);
              }
             
         } catch (SQLException ex) {
             Logger.getLogger(Houses.class.getName()).log(Level.SEVERE, null, ex);
         }
            
           
            
        
        
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(House_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(House_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(House_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(House_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new House_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBoxAgID1;
    private javax.swing.JComboBox jComboBoxEstID;
    private javax.swing.JComboBox jComboBoxLandID;
    private javax.swing.JComboBox jComboBoxSize;
    private javax.swing.JComboBox jComboBoxStat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldrent;
    // End of variables declaration//GEN-END:variables
}
