
import java.awt.print.PrinterException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class Payments extends javax.swing.JFrame {

    myConnection cn= new myConnection();
    p_class pc = new p_class();
    SimpleDateFormat sdt = new SimpleDateFormat(" yyyy-MM-dd HH:mm:ss");
    public Payments() {
        initComponents();
        ComboName();
        this.setLocationRelativeTo(null);
        jDateChooser1.setMaxSelectableDate(new Date());
        jDateChooser1.setMinSelectableDate(new Date());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxName = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldHouseNo = new javax.swing.JTextField();
        jTextFieldRent = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooserDate = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("PAYMENTS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1117, -1));

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 96, 192, 36));

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("PAYMENT ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, 96, 31));

        jLabel3.setBackground(new java.awt.Color(153, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("TENANT NAME");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, 132, 31));

        jTextFieldTId.setEditable(false);
        jTextFieldTId.setAutoscrolls(false);
        jTextFieldTId.setEnabled(false);
        jTextFieldTId.setFocusable(false);
        jTextFieldTId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTIdActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTId, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 218, 192, 31));

        jLabel4.setBackground(new java.awt.Color(153, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setText("TENANT ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 217, -1, 31));

        jComboBoxName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select--" }));
        jComboBoxName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNameItemStateChanged(evt);
            }
        });
        jComboBoxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNameActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 159, 200, 31));

        jLabel5.setBackground(new java.awt.Color(153, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 255, 255));
        jLabel5.setText("HOUSE NO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 353, -1, 31));

        jTextFieldHouseNo.setEditable(false);
        jTextFieldHouseNo.setAutoscrolls(false);
        jTextFieldHouseNo.setEnabled(false);
        jTextFieldHouseNo.setFocusable(false);
        jTextFieldHouseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHouseNoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldHouseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 354, 192, 31));

        jTextFieldRent.setEditable(false);
        jTextFieldRent.setAutoscrolls(false);
        jTextFieldRent.setEnabled(false);
        jTextFieldRent.setFocusable(false);
        jTextFieldRent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRentActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 192, 31));

        jLabel6.setBackground(new java.awt.Color(153, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 255, 255));
        jLabel6.setText("RENT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 31));

        jLabel7.setBackground(new java.awt.Color(153, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 255, 255));
        jLabel7.setText("DATE CHECKEDIN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, 31));

        jTextFieldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmountActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 96, 192, 36));

        jLabel8.setBackground(new java.awt.Color(153, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 255));
        jLabel8.setText("AMOUNT");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 98, 74, 31));

        jLabel9.setBackground(new java.awt.Color(153, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 255));
        jLabel9.setText("DATE");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 158, 74, 31));

        jDateChooserDate.setDateFormatString("yyyy-MM-dd");
        jDateChooserDate.setEnabled(false);
        jDateChooserDate.setFocusable(false);
        jPanel1.add(jDateChooserDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 203, 29));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\pay.png")); // NOI18N
        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 180, -1));

        jDateChooser1.setDateFormatString("yyyy/MM/dd");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 158, 206, 31));

        receipt.setColumns(20);
        receipt.setRows(5);
        jScrollPane1.setViewportView(receipt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(735, 105, 372, 530));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\clear.png")); // NOI18N
        jButton2.setText("CLEAR FIELDS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 250, 40));

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\generate.png")); // NOI18N
        jButton3.setText("GENERATE RECEIPT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 250, 40));

        jButton4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\icons\\Apps-preferences-desktop-printer-icon.png")); // NOI18N
        jButton4.setText("PRINT RECEIPT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jTextFieldTIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTIdActionPerformed

    private void jTextFieldHouseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHouseNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHouseNoActionPerformed

    private void jTextFieldRentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRentActionPerformed

    private void jTextFieldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmountActionPerformed

    
    public void ComboName(){
              PreparedStatement st;
        ResultSet  rs;
        String querySelection = "SELECT * FROM `tenants`";
        
         try {
             st=cn.createConnection().prepareStatement(querySelection);
              rs = st.executeQuery();
              
              while(rs.next()){
                  String LandlordID=rs.getString("Name");
                  jComboBoxName.addItem(LandlordID);
              }
             
         } catch (SQLException ex) {
             Logger.getLogger(Houses.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String ID=String.valueOf(jTextFieldID.getText());
        String houseno=jTextFieldHouseNo.getText();
        String amount=String.valueOf(jTextFieldAmount.getText());
        Date date= jDateChooser1.getDate();
        String dt =sdt.format(date);
        Double rent= Double.parseDouble(jTextFieldRent.getText());
        Double amnt= Double.parseDouble(jTextFieldAmount.getText());
        
      
            
        
        if(ID.trim().equals("") ||houseno.trim().equals("") || amount.trim().equals("")){
            
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> ID, Name and Phone", "Empty fields", JOptionPane.WARNING_MESSAGE);

        }
        else{
            
        if(amnt>rent){
            JOptionPane.showMessageDialog(rootPane, "Excess rent pushed to next month", "Excess Rent", JOptionPane.INFORMATION_MESSAGE);
            
        
        
         if(pc.addPayment(ID, houseno,amount,dt)){
             JOptionPane.showMessageDialog(rootPane, "Successful", "Payment success", JOptionPane.INFORMATION_MESSAGE);
             
         }
         else{
             JOptionPane.showMessageDialog(rootPane, "Unsuccessful", "Payment Error", JOptionPane.ERROR_MESSAGE);
        }
        }
        
        else if(Objects.equals(amnt, rent)){
             if(pc.addPayment(ID, houseno,amount,dt)){
             JOptionPane.showMessageDialog(rootPane, "Successful", "Payment success", JOptionPane.INFORMATION_MESSAGE);
             
         }
         else{
             JOptionPane.showMessageDialog(rootPane, "Unsuccessful", "Payment Error", JOptionPane.ERROR_MESSAGE);
        }
            
            
        }
        
        else{
             JOptionPane.showMessageDialog(rootPane, "Less rent Paid", "Payment Error", JOptionPane.ERROR_MESSAGE);
            
        }
        
    }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNameItemStateChanged
try{
         PreparedStatement st;
            ResultSet rs;
           String query="SELECT\n" +
"tenants.ID,\n" +
"tenants.HouseNumber,\n" +
"houses.Rent,\n" +
"tenants.CheckInDate\n" +
"FROM\n" +
"houses\n" +
"INNER JOIN\n" +
"tenants\n" +
"ON\n" +
"houses.Number=tenants.HouseNumber\n" +
"WHERE tenants.Name='"+jComboBoxName.getSelectedItem()+"';";
            String ID,housenumber,Rent;
            Date checkindate;
            st=cn.createConnection().prepareStatement(query);

            rs=st.executeQuery(query);
            if(rs.next()){
                ID=rs.getString("ID");
                housenumber=rs.getString("HouseNumber");
                Rent=rs.getString("Rent");
                checkindate=rs.getDate("CheckInDate");
               
                jTextFieldTId.setText(ID);
                jTextFieldRent.setText(Rent);
                jTextFieldHouseNo.setText(housenumber);
                jDateChooserDate.setDate(checkindate);
               }
}
catch (SQLException ex) {
            Logger.getLogger(TenantsCheckIn.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
        
    }//GEN-LAST:event_jComboBoxNameItemStateChanged

             
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: 
        receipt.setText("************************************\n");
        receipt.setText(receipt.getText() + "*  Double A Payment Receipt  *\n");
        receipt.setText(receipt.getText() + "************************************\n");
        
        Date dt=new Date();
        String date=dt.toString();
        
        receipt.setText(receipt.getText() + "\n" + date +"\n\n");
        receipt.setText(receipt.getText() + "Payment ID :" + jTextFieldID.getText() +"\n\n");
        receipt.setText(receipt.getText() + "Tenant's ID :" + jTextFieldTId.getText() +"\n\n");
        receipt.setText(receipt.getText() + "Tenant's Name :" + jComboBoxName.getSelectedItem() +"\n\n");
        receipt.setText(receipt.getText() + "House Number :" + jTextFieldHouseNo.getText() +"\n\n");
        receipt.setText(receipt.getText() + "Amount Paid :" + jTextFieldAmount.getText() +"\n\n");
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            receipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Payments.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextFieldID.setText(null);
        jComboBoxName.setSelectedIndex(0);
        jTextFieldTId.setText(null);
        jTextFieldHouseNo.setText(null);
        jTextFieldRent.setText(null);
        jTextFieldAmount.setText(null);
        jDateChooserDate.setDate(null);
        receipt.setText(null);
        jDateChooser1.setDate(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNameActionPerformed

             
   
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBoxName;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooserDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldHouseNo;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldRent;
    private javax.swing.JTextField jTextFieldTId;
    private javax.swing.JTextArea receipt;
    // End of variables declaration//GEN-END:variables
}
